#!/bin/bash

URL="https://pokeapi.co/api/v2/pokemon/pikachu"
OUTPUT_FILE="data.json"
ERROR_FILE="errors.txt"

curl -s --fail "$URL" -o "$OUTPUT_FILE" || echo "Failed to fetch Pikachu data" >> "$ERROR_FILE"
